# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DownloadSelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DownloadSelf
  pod 'GCDWebServer'
  pod "GCDWebServer/WebUploader"
  pod "GCDWebServer/WebDAV"
  target 'DownloadSelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DownloadSelfUITests' do
    # Pods for testing
  end

end
